function SpawnRegions()
	return {
		{ name = "Lake Cumberland", file = "media/maps/LCV2/spawnpoints.lua" },
--		{ name = "Riverside, KY", file = "media/maps/Riverside, KY/spawnpoints.lua" },
--		{ name = "Rosewood, KY", file = "media/maps/Rosewood, KY/spawnpoints.lua" },
--		{ name = "West Point, KY", file = "media/maps/West Point, KY/spawnpoints.lua" },
--		{ name = "Muldraugh, KY", file = "media/maps/Muldraugh, KY/spawnpoints.lua" },
--		{ name = "Crowlake", file = "media/maps/Crowlake/spawnpoints.lua" },
--		{ name = "BuffaloHill", file = "media/maps/BuffaloHill/spawnpoints.lua" },
--		{ name = "Constown", file = "media/maps/Constown/spawnpoints.lua" },
--		{ name = "Kentucky Wilds", file = "media/maps/Kentucky Wilds/spawnpoints.lua" },
--		{ name = "Grapeseed", file = "media/maps/Grapeseed/spawnpoints.lua" },
--		{ name = "Greenport", file = "media/maps/Greenport/spawnpoints.lua" },
--		{ name = "GustonKY", file = "media/maps/GustonKY/spawnpoints.lua" },
--		{ name = "Hartburg", file = "media/maps/Hartburg/spawnpoints.lua" },
--		{ name = "li_township", file = "media/maps/li_township/spawnpoints.lua" },
--		{ name = "TrimbleCountyPowerStation", file = "media/maps/TrimbleCountyPowerStation/spawnpoints.lua" },
--		{ name = "Hopewell, KY", file = "media/maps/Hopewell, KY/spawnpoints.lua" },
--		{ name = "The Museum", file = "media/maps/The Museum/spawnpoints.lua" },
--		{ name = "Tandil", file = "media/maps/Tandil/spawnpoints.lua" },
--		{ name = "Tikitown", file = "media/maps/Tikitown/spawnpoints.lua" },
--		{ name = "PineVille", file = "media/maps/PineVille/spawnpoints.lua" },
--		{ name = "NewEkron", file = "media/maps/NewEkron/spawnpoints.lua" },
--		{ name = "Filtration Plant", file = "media/maps/Filtration Plant/spawnpoints.lua" },
--		{ name = "LittleTownship", file = "media/maps/LittleTownship/spawnpoints.lua" },
--		{ name = "lighthouse", file = "media/maps/lighthouse/spawnpoints.lua" },
--		{ name = "lvinternationalairport", file = "media/maps/lvinternationalairport/spawnpoints.lua" },
--		{ name = "Nettle Township", file = "media/maps/Nettle Township/spawnpoints.lua" },
--		{ name = "NewEllroy", file = "media/maps/NewEllroy/spawnpoints.lua" },
--		{ name = "OakDaleUniversity", file = "media/maps/OakDaleUniversity/spawnpoints.lua" },
--		{ name = "McAlpine Locks and Dam", file = "media/maps/McAlpine Locks and Dam/spawnpoints.lua" },
--		{ name = "OverlookHotel", file = "media/maps/OverlookHotel/spawnpoints.lua" },
--		{ name = "elliotpondec", file = "media/maps/elliotpondec/spawnpoints.lua" },
--		{ name = "Blackwood", file = "media/maps/Blackwood/spawnpoints.lua" },
--		{ name = "Utopia", file = "media/maps/Utopia/spawnpoints.lua" },
--		{ name = "Southwood2.0", file = "media/maps/Southwood2.0/spawnpoints.lua" },
	}
end
